[workspace]
authors = ["Nexuzzz0 <apwd7274@gmail.com>"]
channels = ["conda-forge"]
name = "server"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
run = "python manage.py runserver 0.0.0.0:9003"

[dependencies]
python = "3.12.*"

[pypi-dependencies]
django = "==3.2.11"
pymysql = "==1.0.2"
djangorestframework = "==3.14.0"
django-cors-headers = "==3.13.0"
pillow = ">=9.0.0"
psutil = "==5.9.4"
